import { useMemo, useSyncExternalStore } from "react";
import type { FileDomain } from "../../../shared/ipc";

export type LanguageId = "zh-CN" | "en-US";

interface LanguageDefinition {
  id: LanguageId;
  name: string;
  htmlLang: string;
  direction: "ltr" | "rtl";
}

export interface LanguageSettings {
  languageId: LanguageId;
}

export type TranslationValues = Record<string, string | number>;
export type TranslationFunction = (
  key: TranslationKey,
  values?: TranslationValues,
) => string;

const LANGUAGE_SETTINGS_KEY = "asteria.language-settings.v1";
const LANGUAGE_SETTINGS_EVENT = "asteria:language-settings-changed";
const LANGUAGE_SETTINGS_CHANNEL = "asteria-language-settings";

const zhCNTranslations = {
  "common.add": "添加",
  "common.apply": "应用",
  "common.appliedFeedback": "√已应用",
  "common.close": "关闭",
  "common.delete": "删除",
  "common.export": "导出",
  "common.loading": "加载中",
  "common.noConfig": "没有配置",
  "common.none": "无",
  "common.noEntries": "没有条目",
  "common.noTags": "没有标签",
  "common.openConfigFile": "打开配置文件",
  "common.refresh": "刷新",
  "common.rename": "重命名",
  "common.cancel": "取消",
  "common.save": "保存",
  "common.savedFeedback": "√已保存",
  "common.modify": "修改",
  "common.favorite": "喜欢",
  "common.unfavorite": "取消喜欢",
  "common.adjustWidth": "调整宽度",
  "common.adjustHeight": "调整高度",

  "app.emptyPage": "空页面",
  "app.noOpenPage": "没有打开的页面",
  "app.pageList": "页面列表",
  "app.pageName": "页面 {index}",
  "app.pageNameEmpty": "页面名称为空",
  "app.pageNameInput": "页面名称",
  "app.pageNamePlaceholder": "输入页面名称",
  "app.unknownView": "未知视图",
  "app.status.duplicateConfirmMessage":
    "这个文件与 {domainName} 中的文件相同，确定要重复导入吗，这不会创建一个新的文件，只会创建一条新的数据库记录",
  "app.status.duplicateConfirmTitle": "确认重复导入",
  "app.status.importFailed": "导入失败",
  "app.status.noDroppedPathOrUrl": "未读取到拖入路径或链接",
  "app.status.preloadUnavailable": "预加载不可用",
  "app.status.ready": "就绪",
  "app.status.scanDroppedContent": "扫描拖入内容",
  "app.status.waitingImport": "等待导入",
  "app.status.waitingSelectFiles": "等待选择文件",
  "app.status.waitingSelectFolder": "等待选择文件夹",
  "app.workStatus":
    "{message} 队列 {queued} 处理中 {processing} 已完成 {completed}",
  "app.workStatus.thumbnailReady": "缓存就绪",
  "app.workStatus.thumbnailGenerating": "正在生成缩略图",
  "app.workStatus.aiIdle": "模型打标空闲",
  "app.workStatus.aiTagging": "正在模型打标",
  "app.workStatus.aiDone": "模型打标完成",
  "app.workStatus.imageConversionIdle": "图片转换空闲",
  "app.workStatus.imageConverting": "正在转换图片为 PNG: {name}",
  "app.workStatus.tagTranslationIdle": "标签翻译空闲",
  "app.workStatus.tagTranslating": "正在翻译标签",
  "app.workStatus.tagTranslationDone": "标签翻译完成",
  "app.domain.pending": "待入库",
  "app.domain.library": "已在库中",
  "app.domain.trash": "回收站",

  "app.menu.database": "数据库",
  "app.menu.extension": "扩展功能",
  "app.menu.file": "文件",
  "app.menu.page": "页面",
  "app.menu.service": "服务",
  "app.menu.view": "视图",
  "app.action.ai": "人工智能",
  "app.action.api": "API",
  "app.action.browser": "浏览",
  "app.action.ehentaiImport": "从 E-Hentai 导入",
  "app.action.favorites": "我的收藏",
  "app.action.hydrusImport": "从 Hydrus 导入",
  "app.action.import": "导入",
  "app.action.importFiles": "导入文件",
  "app.action.importFilesTitle": "选择一个或多个媒体文件",
  "app.action.importFolder": "导入文件夹",
  "app.action.importFolderTitle": "选择一个文件夹并导入其中媒体文件",
  "app.action.manageTags": "管理标签",
  "app.action.newPage": "新建页面",
  "app.action.rating": "分级",
  "app.action.recycleBin": "回收站",
  "app.action.saveLayout": "保存布局",
  "app.action.search": "搜索",
  "app.action.settings": "设置",
  "app.action.tagTranslation": "标签翻译",
  "app.action.tags": "标签",
  "app.action.viewDatabase": "查看数据库",

  "settings.category.appearance": "外观",
  "settings.category.file": "文件",
  "settings.category.interface": "界面",
  "settings.category.language": "多语言",
  "settings.category.network": "网络",
  "settings.category.shortcut": "快捷键",
  "settings.file.convertImportedImagesToPng": "导入图片转为 PNG",
  "settings.file.fileStoragePath": "文件存储位置",
  "settings.file.fileStoragePlaceholder": "输入文件存储位置",
  "settings.file.thumbnailStoragePath": "缩略图缓存位置",
  "settings.file.thumbnailStoragePlaceholder": "输入缩略图缓存位置",
  "settings.interface.browser": "浏览",
  "settings.interface.browserPageSize": "单页文件数",
  "settings.interface.browserPageSizePlaceholder": "输入单页文件数",
  "settings.interface.configName": "配置名称",
  "settings.interface.configNamePlaceholder": "输入配置名称",
  "settings.interface.defaultImportPage": "默认导入页",
  "settings.interface.defaultNewPage": "默认新标签页",
  "settings.interface.deleteConfig": "删除配置",
  "settings.interface.layoutConfigCount": "{count} 个配置",
  "settings.interface.layoutConfigNotLoaded": "未加载",
  "settings.interface.newConfig": "新建配置",
  "settings.interface.pageLayout": "页面配置",
  "settings.language.interfaceLanguage": "界面语言",
  "settings.language.languageSettings": "语言设置",
  "settings.network.enableProxy": "启用代理",
  "settings.network.proxyAddress": "代理地址",
  "settings.network.proxyAddressPlaceholder": "输入代理地址，例如 127.0.0.1",
  "settings.network.proxyPort": "代理端口",
  "settings.network.proxyPortPlaceholder": "输入代理端口",
  "settings.shortcut.deleteShortcut": "删除快捷键",
  "settings.shortcut.recording": "按键...",
  "settings.shortcut.resetDefaults": "恢复默认",
  "settings.shortcut.closeWindow": "关闭当前窗口",
  "settings.shortcut.closeWindowDesc": "主窗口除外",
  "settings.shortcut.selectAll": "全选当前条目",
  "settings.shortcut.selectAllDesc": "只作用于当前可多选区域",
  "settings.shortcut.detailPreviousFile": "详情上一文件",
  "settings.shortcut.detailPreviousFileDesc": "文件详情窗口",
  "settings.shortcut.detailNextFile": "详情下一文件",
  "settings.shortcut.detailNextFileDesc": "文件详情窗口",
  "settings.shortcut.browserPreviousPage": "浏览上一页",
  "settings.shortcut.browserPreviousPageDesc": "浏览 view",
  "settings.shortcut.browserNextPage": "浏览下一页",
  "settings.shortcut.browserNextPageDesc": "浏览 view",
  "settings.theme.theme": "主题",
  "settings.theme.themeSettings": "主题设置",
  "settings.theme.default": "默认主题",
  "settings.theme.light": "浅色主题",
  "window.dialog.loading": "加载中",
  "window.export.failed": "导出失败",
  "window.export.file": "文件",
  "window.export.filename": "文件名",
  "window.export.inputFormat": "输入导出文件名格式",
  "window.export.inputPath": "输入导出路径",
  "window.export.noFormat": "无格式",
  "window.export.path": "路径",
  "window.export.waiting": "等待导出",
  "window.batchOperation.title": "批操作",
  "window.batchOperation.loading": "未加载",
  "window.batchOperation.invalid": "文件无效",
  "window.batchOperation.count": "{count} 个文件，{imageCount} 张图片",
  "window.batchOperation.processing": "正在处理 {current} / {total}: {name}",
  "window.batchOperation.complete": "完成：{count} 张图片",
  "window.batchOperation.logs": "处理日志",
  "window.batchOperation.noLogs": "暂无日志",
  "window.batchOperation.description":
    "函数接收 context，可读取文件元数据、标签和 URL，并可批量编辑标签与 URL。",
  "window.batchOperation.resetExample": "重置示例",
  "window.batchOperation.run": "运行",
  "window.batchOperation.running": "处理中",
  "window.batchOperation.compileFailed": "脚本无法运行",
  "window.batchOperation.notFunction": "脚本必须返回一个函数",
  "window.batchOperation.processFailed": "处理失败",
  "window.batchOperation.metadataProcessed": "已处理元数据",
  "window.batchOperation.urlMissing": "URL 不存在",
  "window.batchTagManager.title": "批量标签管理",
  "window.fileRatingEditor.title": "设置分级",
  "window.favorite.fileCount": "{count} 个文件",
  "window.favorite.updateFailed": "收藏更新失败",
  "window.favorite.noFiles": "没有收藏文件",
  "window.translation.csvHint": "CSV 格式：1girl,0,1个女孩",
  "window.translation.csvPlaceholder": "输入标签翻译 CSV 路径",
  "window.translation.csvPath": "标签翻译 CSV 路径",
  "window.translation.enableMenu": "启用右键菜单翻译标签",
  "window.translation.file": "翻译文件",
  "window.translation.notLoaded": "未加载",
  "window.translation.keepOriginal": "在数据库中保留原标签",
  "window.translation.loaded": "配置已加载",
  "window.translation.saved": "配置已保存",
  "window.translation.translateOnCreate": "创建标签时尝试翻译",
  "window.url.add": "新增",
  "window.url.addInput": "新增url",
  "window.url.addPlaceholder": "输入url以增加",
  "window.url.edit": "修改",
  "window.url.invalidFile": "文件无效",
  "window.url.list": "url列表",
  "window.url.loadFailed": "加载失败",
  "window.url.noUrl": "没有url",
  "window.url.sharedList": "{count} 个文件的共同url",
  "window.url.title": "管理URL",
  "window.database.loading": "加载中",
  "window.database.readonly": "只读",
  "window.database.loadFailed": "加载失败",
  "window.database.noRecords": "没有文件记录",
  "window.database.id": "ID",
  "window.database.extension": "扩展名",
  "window.database.size": "大小",
  "window.database.importedAt": "导入时间",
  "window.database.pageSummary":
    "第 {page} / {totalPages} 页，总计 {total} 个文件，{message}",
  "window.database.previous": "上一页",
  "window.database.next": "下一页",
  "window.api.loading": "未加载",
  "window.api.preloadUnavailable": "preload unavailable",
  "window.api.serviceList": "服务列表",
  "window.api.noServices": "没有 API 服务",
  "window.api.createInput": "新建 API",
  "window.api.createPlaceholder": "输入 API 名称",
  "window.api.create": "新建",
  "window.api.defaultServiceName": "API 服务",
  "window.api.enable": "启用",
  "window.api.delete": "删除",
  "window.api.check": "检查",
  "window.api.name": "名称",
  "window.api.address": "地址",
  "window.api.port": "端口",
  "window.api.token": "校验 token",
  "window.api.permissions": "权限",
  "window.api.noServiceSelected": "请新建 API 服务",
  "window.api.success": "{count} 个 API 服务",
  "window.api.deleted": "已删除",
  "window.api.namePlaceholder": "输入 API 名称",
  "window.api.addressPlaceholder": "输入 API 地址",
  "window.api.portPlaceholder": "输入 API 端口",
  "window.api.tokenPlaceholder": "输入校验 token",
  "window.rating.loading": "未加载",
  "window.rating.preloadUnavailable": "preload unavailable",
  "window.rating.group": "分级",
  "window.rating.noGroups": "没有分级",
  "window.rating.createInput": "新建分级",
  "window.rating.createPlaceholder": "输入分级以新建",
  "window.rating.create": "新建",
  "window.rating.name": "分级名称",
  "window.rating.namePlaceholder": "输入分级名称",
  "window.rating.rename": "重命名",
  "window.rating.activate": "激活",
  "window.rating.deactivate": "停用",
  "window.rating.delete": "删除",
  "window.rating.entryInput": "新建条目",
  "window.rating.entryPlaceholder": "输入分级条目",
  "window.rating.entryCreate": "新建条目",
  "window.rating.entryColor": "条目颜色",
  "window.rating.entryCount": "{count} 个条目",
  "window.rating.noEntries": "没有条目",
  "window.rating.dragHint": "拖动调整顺序",
  "window.recycle.loading": "未加载",
  "window.recycle.preloadUnavailable": "preload unavailable",
  "window.recycle.confirmDeleteTitle": "确认彻底删除",
  "window.recycle.confirmDeleteMessage": "确认彻底删除 {count} 个文件吗",
  "window.recycle.confirmClearTitle": "确认清空回收站",
  "window.recycle.confirmClearMessage":
    "确认彻底删除回收站中的 {count} 个文件吗",
  "window.recycle.noRecords": "没有文件记录",
  "window.recycle.restore": "还原",
  "window.recycle.delete": "彻底删除",
  "window.recycle.restoreAll": "一键还原",
  "window.recycle.deleteAll": "一键彻底删除",
  "window.recycle.previous": "上一页",
  "window.recycle.next": "下一页",
  "window.batch.loading": "未加载",
  "window.batch.invalid": "文件无效",
  "window.batch.count": "{count} 个文件",
  "window.batch.noTags": "没有标签",
  "window.batch.input": "输入标签",
  "window.batch.placeholder": "输入标签以增加",
  "window.fileRating.loading": "加载中",
  "window.fileRating.invalid": "参数无效",
  "window.fileRating.missing": "分级不存在",
  "window.fileRating.loadFailed": "加载失败",
  "window.fileRating.group": "分级",
  "window.fileRating.files": "{count} 个文件",
  "window.fileRating.noEntries": "没有条目",
  "window.fileRating.cancel": "取消",
  "window.fileRating.save": "保存",
  "window.tagManager.loading": "未加载",
  "window.tagManager.loadedStyle": "{count} 个风格",
  "window.tagManager.createdStyle": "已创建风格",
  "window.tagManager.createFailed": "创建失败",
  "window.tagManager.createdTags": "已创建 {count} 个标签",
  "window.tagManager.activatedStyle": "已启用风格",
  "window.tagManager.activateFailed": "启用失败",
  "window.tagManager.renamedStyle": "已重命名风格",
  "window.tagManager.renameFailed": "重命名失败",
  "window.tagManager.confirmDeleteStyleTitle": "确认删除标签风格",
  "window.tagManager.confirmDeleteStyleMessage":
    "这将删除风格“{name}”下的 {count} 个标签，并移除相关文件标签关联，确认吗",
  "window.tagManager.deletedStyle": "已删除风格，删除 {count} 个标签",
  "window.tagManager.deleteStyleFailed": "删除风格失败",
  "window.tagManager.confirmDeleteTagsTitle": "确认删除标签",
  "window.tagManager.deletedTags":
    "已删除 {tagCount} 个标签，影响 {fileCount} 个文件",
  "window.tagManager.deleteFailed": "删除失败",
  "window.tagManager.styleList": "标签风格",
  "window.tagManager.currentStyleTags": "当前风格标签",
  "window.tagManager.searchTags": "搜索标签",
  "window.tagManager.searchTagsPlaceholder": "搜索当前风格标签",
  "window.tagManager.newStyle": "新建风格",
  "window.tagManager.newStylePlaceholder": "输入风格以新建",
  "window.tagManager.create": "新建",
  "window.tagManager.renameStyle": "重命名风格",
  "window.tagManager.renameStylePlaceholder": "输入风格以重命名",
  "window.tagManager.rename": "改名",
  "window.tagManager.deleteStyle": "删除",
  "window.tagManager.sortField": "排序字段",
  "window.tagManager.sortName": "字母",
  "window.tagManager.sortCreatedAt": "创建时间",
  "window.tagManager.sortFileCount": "引用数量",
  "window.tagManager.sortDirection": "排序方向",
  "window.tagManager.sortAsc": "增序",
  "window.tagManager.sortDesc": "降序",
  "window.tagManager.enableStyle": "启用风格",
  "window.tagManager.noTags": "没有标签",
  "window.tagManager.selectedCount": "已选 {count} 个标签",
  "window.tagManager.delete": "删除",
  "window.tagManager.parents": "父子级语义",
  "window.tagManager.parentAddFailed": "添加父子级关系失败",
  "window.tagManager.parentRemoveFailed": "删除父子级关系失败",
  "window.tagManager.parentRelationsAdded": "已添加 {count} 条关系",
  "window.tagManager.parentRelationsRemoved": "已删除 {count} 条关系",
  "window.tagManager.relationErrorTitle": "标签关系错误",
  "window.tagManager.parentSelfRelation": "标签不能成为自己的父级",
  "window.tagManager.siblingSelfRelation": "别名标签不能指向自己",
  "window.tagManager.noStyleSelected": "未选择标签风格",
  "window.tagManager.styleSummary": "{count} 个标签",
  "window.tagManager.stagingArea": "待操作区",
  "window.tagManager.stagingCount": "{count} 个待操作标签",
  "window.tagManager.noStagedTags": "没有待操作标签",
  "window.tagManager.basicInfo": "基本信息",
  "window.tagManager.tagRelations": "标签关联性",
  "window.tagManager.existingTags": "已存在标签",
  "window.tagManager.tagsToCreate": "待创建标签",
  "window.tagManager.createTagInput": "创建标签",
  "window.tagManager.createTagPlaceholder": "键入新标签以创建",
  "window.tagManager.tagAlreadyExists": "标签已存在",
  "window.tagManager.tagAlreadyPendingCreate": "标签已在待创建列表中",
  "window.tagManager.invalidTagInput": "请输入有效标签",
  "window.tagManager.nameColumn": "名称",
  "window.tagManager.fileCountColumn": "文件数量",
  "window.tagManager.createdAtColumn": "创建日期",
  "window.tagManager.operationColumn": "操作",
  "window.tagManager.noExistingStagedTags": "没有已存在标签",
  "window.tagManager.noMissingStagedTags": "没有待创建标签",
  "window.tagManager.stagedTags": "已放入 {count} 个标签",
  "window.tagManager.renameTag": "重命名标签",
  "window.tagManager.renamedTag": "已重命名标签",
  "window.tagManager.renamePreview": "影响预览",
  "window.tagManager.renamePreviewLoading": "正在计算影响",
  "window.tagManager.renamePreviewFailed": "影响预览失败",
  "window.tagManager.renamePreviewFiles":
    "直接影响 {directCount} 个文件；语义搜索可命中 {effectiveCount} 个文件，其中 {impliedCount} 个来自推导。",
  "window.tagManager.renamePreviewParents":
    "父级关系 {parentCount} 条，子级关系 {childCount} 条。",
  "window.tagManager.renamePreviewSiblings":
    "作为标准标签拥有 {aliasCount} 个别名；作为别名指向 {canonicalCount} 个标准标签。",
  "window.tagManager.renamePreviewDuplicate": "目标标签已存在，保存会失败。",
  "window.tagManager.invalidTag": "标签无效",
  "window.tagManager.confirmDeleteSingleTagMessage":
    "这将删除标签“{name}”，并从相关文件中移除这个标签，确认吗",
  "window.tagManager.relationSourceTags": "待操作标签",
  "window.tagManager.addParentInput": "添加父级标签",
  "window.tagManager.addChildInput": "添加子级标签",
  "window.tagManager.addParentPlaceholder": "键入以添加父级",
  "window.tagManager.addChildPlaceholder": "键入以添加子级",
  "window.tagManager.addRelation": "添加",
  "window.tagManager.noRelationSourceSelected": "请先选择待操作标签",
  "window.tagManager.noCommonParents": "没有共同父级标签",
  "window.tagManager.noCommonChildren": "没有共同子级标签",
  "window.tagManager.setSelectedChildren": "将选中标签设为子级",
  "window.tagManager.commonParents": "共同父级标签",
  "window.tagManager.setSelectedParents": "将选中标签设为父级",
  "window.tagManager.commonChildren": "共同子级标签",
  "window.tagManager.selectedRelationTags": "选中标签",
  "window.tagManager.removeRelation": "移除",
  "window.tagManager.openRelationTree": "打开关系树",
  "window.tagManager.noRelationTreeTags": "没有可打开的关系树标签",
  "window.tagManager.aliasesAndCanonical": "别名与标准标签",
  "window.tagManager.setSelectedAliases": "将选中标签设为别名",
  "window.tagManager.setCanonicalInput": "设置标准标签",
  "window.tagManager.setCanonicalPlaceholder": "键入以设置标准标签",
  "window.tagManager.setCanonical": "设置标准",
  "window.tagManager.commonCanonical": "共同标准标签",
  "window.tagManager.addAliasesToCanonical": "为标准标签添加别名",
  "window.tagManager.addAliasesInput": "添加别名标签",
  "window.tagManager.addAliasesPlaceholder": "键入以添加别名",
  "window.tagManager.selectSingleCanonicalTag": "选择一个标准标签",
  "window.tagManager.addAliases": "添加别名",
  "window.tagManager.aliasesOfSelectedTags": "选中标签的别名",
  "window.tagManager.removeSibling": "移除",
  "window.tagManager.noCommonCanonicalTags": "没有共同标准标签",
  "window.tagManager.noAliasTags": "没有别名标签",
  "window.tagManager.siblingsSet": "已设置 {count} 个标准标签",
  "window.tagManager.siblingsRemoved": "已移除 {count} 个别名关系",
  "window.tagManager.siblingSetFailed": "设置标准标签失败",
  "window.tagManager.siblingRemoveFailed": "移除别名关系失败",
  "window.tagRelationTree.title": "标签关系树",
  "window.tagRelationTree.siblingTitle": "标签别名关系树",
  "window.tagRelationTree.loading": "正在加载关系树",
  "window.tagRelationTree.loadFailed": "关系树加载失败",
  "window.tagRelationTree.noSelection": "没有选择标签",
  "window.tagRelationTree.loaded": "{nodeCount} 个标签，{edgeCount} 条关系",
  "window.tagRelationTree.summary":
    "选中 {selectedCount}，节点 {nodeCount}，关系 {edgeCount}",
  "window.tagRelationTree.fit": "适应",
  "window.tagRelationTree.readonly": "只读关系树",
  "window.ai.loading": "未加载",
  "window.ai.loaded": "配置已加载",
  "window.ai.saved": "配置已保存",
  "window.ai.detecting": "正在检测模型",
  "window.ai.detected": "已检测到 {count} 个模型",
  "window.ai.noModel": "未检测到模型",
  "window.ai.downloading": "正在下载默认模型",
  "window.ai.ready": "默认模型已就绪",
  "window.ai.noModelDetected": "未检测到模型",
  "window.ai.modelConfig": "模型配置",
  "window.ai.featureConfig": "功能配置",
  "window.ai.path": "路径",
  "window.ai.pathPlaceholder": "输入模型文件夹路径",
  "window.ai.detectModel": "检测模型",
  "window.ai.downloadDefault": "下载默认模型",
  "window.ai.model": "模型",
  "window.ai.selectModel": "选择模型",
  "window.ai.noneSelected": "未选择",
  "window.ai.generalThreshold": "普通阈值",
  "window.ai.characterThreshold": "角色阈值",
  "window.ai.thresholdPlaceholder": "输入 0-1",
  "window.ai.info": "模型信息",
  "window.ai.modelName": "模型名称",
  "window.ai.modelCount": "模型数量",
  "window.ai.modelSize": "模型大小",
  "window.ai.enableAutoTag": "当导入图片没有任何标签时启用模型打标",
  "window.ai.enableRetag": "启用右键菜单为选中图片重新打标（覆盖）",
  "window.ai.enableAppend": "启用右键菜单为选中图片追加标签（追加）",
  "window.hydrus.loading": "未开始",
  "window.hydrus.waiting": "等待操作",
  "window.hydrus.preloadUnavailable": "preload 不可用，请重启应用",
  "window.hydrus.preloadAvailable": "preload 可用",
  "window.hydrus.loaded": "配置已加载",
  "window.hydrus.saved": "配置已保存",
  "window.hydrus.testConnectionIgnored": "测试连接被忽略：正在执行任务",
  "window.hydrus.apiUnavailable": "Hydrus 导入 API 不可用，请重启应用",
  "window.hydrus.testingConnection": "正在测试连接",
  "window.hydrus.testConnection": "测试连接",
  "window.hydrus.connectionSucceeded": "连接成功：{message}",
  "window.hydrus.connectionFailed": "连接失败：{message}",
  "window.hydrus.testConnectionFailed": "测试连接失败",
  "window.hydrus.startImportIgnored": "开始导入被忽略：正在执行任务",
  "window.hydrus.importMissing": "importFromHydrus 不存在",
  "window.hydrus.preparingImport": "准备 Hydrus 导入",
  "window.hydrus.importSummary":
    "导入结束：新增={imported} 重复对象={duplicated} 跳过={skipped} 失败={failed}",
  "window.hydrus.importFailed": "Hydrus 导入失败",
  "window.hydrus.startImport": "开始导入",
  "window.hydrus.cancelImport": "取消",
  "window.hydrus.address": "地址",
  "window.hydrus.addressPlaceholder": "输入 Hydrus API 地址",
  "window.hydrus.accessKey": "Access Key",
  "window.hydrus.accessKeyPlaceholder": "输入 Hydrus Access Key",
  "window.hydrus.tagStyle": "标签风格",
  "window.hydrus.tagStylePlaceholder": "输入迁移标签风格",
  "window.hydrus.limit": "数量限制",
  "window.hydrus.limitPlaceholder": "0 表示不限",
  "window.hydrus.metadataBatchSize": "元数据分片",
  "window.hydrus.metadataBatchSizePlaceholder": "输入元数据分片大小",
  "window.hydrus.duplicateAsNewObject": "重复文件创建新对象",
  "window.hydrus.searchTags": "搜索标签",
  "window.hydrus.searchTagsPlaceholder":
    "输入 Hydrus 搜索标签，使用逗号或换行分隔；空白表示全部",
  "window.hydrus.total": "总数",
  "window.hydrus.processed": "已处理",
  "window.hydrus.added": "新增",
  "window.hydrus.duplicated": "重复对象",
  "window.hydrus.skipped": "跳过",
  "window.hydrus.failed": "失败",
  "window.hydrus.current": "当前",
  "window.hydrus.connectionStatus": "连接状态",
  "window.hydrus.permissions": "权限",
  "window.hydrus.notTested": "未测试",
  "window.hydrus.debug": "Debug",
  "window.hydrus.clear": "清空",
  "window.hydrus.noDebugInfo": "没有 debug 信息",
  "window.ehentai.loading": "未开始",
  "window.ehentai.waiting": "等待操作",
  "window.ehentai.preloadUnavailable": "preload 不可用，请重启应用",
  "window.ehentai.loaded": "配置已加载",
  "window.ehentai.saved": "配置已保存",
  "window.ehentai.apiUnavailable": "E-Hentai API 不可用，请重启应用",
  "window.ehentai.detectingGalleryLink": "检测 gallery 链接",
  "window.ehentai.testingGallery": "正在检测链接",
  "window.ehentai.detectSuccess": "检测成功：{message}",
  "window.ehentai.detectFailed": "检测失败：{message}",
  "window.ehentai.detectException": "检测异常：{message}",
  "window.ehentai.preparingImport": "准备 E-Hentai 导入",
  "window.ehentai.importSummary":
    "导入结束：新增={imported} 重复对象={duplicated} 失败={failed}",
  "window.ehentai.importFailed": "E-Hentai 导入失败",
  "window.ehentai.importException": "导入异常：{message}",
  "window.ehentai.startImport": "开始导入",
  "window.ehentai.cancelImport": "取消",
  "window.ehentai.testGallery": "检测链接",
  "window.ehentai.galleryUrl": "Gallery 链接",
  "window.ehentai.galleryUrlPlaceholder": "输入 https://e-hentai.org/g/...",
  "window.ehentai.cookie": "Cookie",
  "window.ehentai.cookiePlaceholder": "输入浏览器复制出的 Cookie",
  "window.ehentai.importGalleryTags": "导入 gallery 标签",
  "window.ehentai.duplicateAsNewObject": "重复文件创建新对象",
  "window.ehentai.startIndex": "起始序号",
  "window.ehentai.startIndexHint":
    "从 gallery 第几张开始，最小为 1；中断后可填下一张序号继续。",
  "window.ehentai.limit": "数量限制",
  "window.ehentai.limitPlaceholder": "0 表示不限",
  "window.ehentai.limitHint":
    "本次最多导入多少张，0 表示从起始序号开始直到结尾。",
  "window.ehentai.requestTimeout": "请求超时 ms",
  "window.ehentai.total": "总数",
  "window.ehentai.processed": "已处理",
  "window.ehentai.added": "新增",
  "window.ehentai.duplicated": "重复对象",
  "window.ehentai.skipped": "跳过",
  "window.ehentai.failed": "失败",
  "window.ehentai.current": "当前",
  "window.ehentai.galleryStatus": "Gallery 状态",
  "window.ehentai.imageCount": "首页: {count}",
  "window.ehentai.style": "风格: e-hentai",
  "window.ehentai.notDetected": "未检测",
  "window.ehentai.importRules": "导入规则",
  "window.ehentai.ruleDescription":
    "默认写入 e-hentai 风格标签 gallery:gallery名字；勾选导入 gallery 标签后，会同时写入页面中的标签。重复文件默认跳过，勾选重复文件创建新对象后会复用物理文件。请求冷却固定为 10000ms。",
  "window.ehentai.logs": "日志",
  "window.ehentai.clear": "清空",
  "window.ehentai.noLogs": "没有日志",
  "window.fileDetail.invalid": "文件无效",
  "window.fileDetail.notFound": "文件不存在",
  "window.fileDetail.loadFailed": "加载失败",
  "window.fileDetail.favoriteUpdateFailed": "收藏更新失败",
  "window.fileDetail.movedToRecycleBin": "文件已放入回收站",
  "window.fileDetail.filterComplete": "筛选完成",
  "window.fileDetail.cannotPreview": "无法预览",
  "window.fileDetail.tags": "文件标签",
  "window.fileDetail.inferredTags": "推导标签",
  "window.fileDetail.inferredTagTitle": "{tag}，由父子级关系推导",
  "window.fileDetail.canonicalTagTitle": "{tag}，由别名关系映射到标准标签",
  "window.fileDetail.addTags": "输入标签以增加",
  "window.fileDetail.title": "文件详情",

  "window.import.now": "现在导入",
  "window.import.cancel": "取消",
  "window.import.dropHint": "松开导入媒体文件或文件夹",
  "window.import.batch": "批次",
  "window.import.total": "总数",
  "window.import.ready": "可导入",
  "window.import.added": "新增",
  "window.import.duplicate": "重复",
  "window.import.failed": "失败",
  "window.import.chunk": "分片",
  "window.import.currentFile": "当前文件",
  "window.import.status": "状态",
  "window.import.size": "大小",
  "window.import.extension": "扩展名",
  "window.import.path": "路径",
  "window.import.noFiles": "没有待导入文件",
  "window.search.locked": "不可操作，因为正在导入文件",
  "window.search.input": "搜索",
  "window.search.placeholder": "输入标签以搜索",
  "window.search.noFilters": "没有筛选项",
  "window.screening.title": "筛选入库",
  "window.browser.loading": "加载中",
  "window.browser.loadFailed": "加载失败",
  "window.browser.favoriteFailed": "收藏更新失败",
  "window.browser.pendingCount": "{count} 个待导入文件",
  "window.browser.resultCount": "{count} 个结果",
  "window.browser.fileCount": "{count} 个文件",
  "window.browser.noRecords": "没有文件记录",
  "window.browser.pending": "待导入",
  "window.browser.sort": "排序",
  "window.browser.sortField": "浏览排序字段",
  "window.browser.sortDirection": "浏览排序方向",
  "window.browser.importedAt": "导入日期",
  "window.browser.updatedAt": "修改日期",
  "window.browser.desc": "降序",
  "window.browser.asc": "升序",
  "window.browser.firstPage": "首页",
  "window.browser.previousPage": "上页",
  "window.browser.pageInput": "浏览页码",
  "window.browser.nextPage": "下页",
  "window.browser.lastPage": "末页",
  "window.contextMenu.manageUrl": "管理url",
  "window.contextMenu.manageTags": "管理标签",
  "window.contextMenu.batchOperate": "批量操作",
  "window.contextMenu.openDefault": "使用默认方式打开",
  "window.contextMenu.aiRetagOverwrite": "使用模型打标（覆盖）",
  "window.contextMenu.aiRetagAppend": "使用模型打标（追加）",
  "window.contextMenu.translateTags": "翻译标签",
  "window.contextMenu.export": "导出",
  "window.contextMenu.screening": "筛选入库",
  "window.contextMenu.ratingSet": "设置:{name}",
  "window.contextMenu.trash": "放入回收站",
  "window.tagList.loading": "未加载",
  "window.tagList.preloadUnavailable": "preload unavailable",
  "window.tagList.loadedTags": "{count} 个标签",
  "window.tagList.loadFailed": "加载失败",
  "window.tagList.displayRange": "标签显示范围",
  "window.tagList.all": "全部",
  "window.tagList.namespace": "命名空间",
  "window.tagList.plain": "普通标签",
  "window.tagList.selection": "选中",
  "window.tagList.sortAlphabetical": "字母排序",
  "window.tagList.ascending": "字母升序",
  "window.tagList.descending": "字母降序",
  "window.tagList.namespaceFirst": "命名空间优先",
  "window.tagList.locked": "不可操作，因为正在导入文件",
  "window.tagList.domains": "域",
  "window.tagList.noDomains": "没有域",
  "window.tagList.noTags": "没有标签",
};

export type TranslationKey = keyof typeof zhCNTranslations;

const enUSTranslations: Record<TranslationKey, string> = {
  "common.add": "Add",
  "common.apply": "Apply",
  "common.appliedFeedback": "Applied",
  "common.close": "Close",
  "common.delete": "Delete",
  "common.export": "Export",
  "common.loading": "Loading",
  "common.noConfig": "No configs",
  "common.none": "None",
  "common.noEntries": "No entries",
  "common.noTags": "No tags",
  "common.openConfigFile": "Open config file",
  "common.refresh": "Refresh",
  "common.rename": "Rename",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.savedFeedback": "Saved",
  "common.modify": "Modify",
  "common.favorite": "Favorite",
  "common.unfavorite": "Unfavorite",
  "common.adjustWidth": "Adjust width",
  "common.adjustHeight": "Adjust height",

  "app.emptyPage": "Empty page",
  "app.noOpenPage": "No open page",
  "app.pageList": "Pages",
  "app.pageName": "page {index}",
  "app.pageNameEmpty": "Page name is empty",
  "app.pageNameInput": "Page name",
  "app.pageNamePlaceholder": "Enter page name",
  "app.unknownView": "Unknown view",
  "app.status.duplicateConfirmMessage":
    "This file is identical to a file in {domainName}. Import it again? This will not create a new physical file, only a new database record.",
  "app.status.duplicateConfirmTitle": "Confirm Duplicate Import",
  "app.status.importFailed": "Import failed",
  "app.status.noDroppedPathOrUrl": "No dropped path or URL was found",
  "app.status.preloadUnavailable": "Preload unavailable",
  "app.status.ready": "Ready",
  "app.status.scanDroppedContent": "Scanning dropped content",
  "app.status.waitingImport": "Waiting for import",
  "app.status.waitingSelectFiles": "Waiting for file selection",
  "app.status.waitingSelectFolder": "Waiting for folder selection",
  "app.workStatus":
    "{message} Queue {queued} Processing {processing} Completed {completed}",
  "app.workStatus.thumbnailReady": "Cache ready",
  "app.workStatus.thumbnailGenerating": "Generating thumbnails",
  "app.workStatus.aiIdle": "AI tagging idle",
  "app.workStatus.aiTagging": "AI tagging",
  "app.workStatus.aiDone": "AI tagging complete",
  "app.workStatus.imageConversionIdle": "Image conversion idle",
  "app.workStatus.imageConverting": "Converting image to PNG: {name}",
  "app.workStatus.tagTranslationIdle": "Tag translation idle",
  "app.workStatus.tagTranslating": "Translating tags",
  "app.workStatus.tagTranslationDone": "Tag translation complete",
  "app.domain.pending": "Pending",
  "app.domain.library": "In Library",
  "app.domain.trash": "Recycle Bin",

  "app.menu.database": "Database",
  "app.menu.extension": "Extensions",
  "app.menu.file": "File",
  "app.menu.page": "Page",
  "app.menu.service": "Service",
  "app.menu.view": "View",
  "app.action.ai": "AI",
  "app.action.api": "API",
  "app.action.browser": "Browser",
  "app.action.ehentaiImport": "Import from E-Hentai",
  "app.action.favorites": "Favorites",
  "app.action.hydrusImport": "Import from Hydrus",
  "app.action.import": "Import",
  "app.action.importFiles": "Import Files",
  "app.action.importFilesTitle": "Select one or more media files",
  "app.action.importFolder": "Import Folder",
  "app.action.importFolderTitle": "Select a folder and import media files",
  "app.action.manageTags": "Manage Tags",
  "app.action.newPage": "New Page",
  "app.action.rating": "Ratings",
  "app.action.recycleBin": "Recycle Bin",
  "app.action.saveLayout": "Save Layout",
  "app.action.search": "Search",
  "app.action.settings": "Settings",
  "app.action.tagTranslation": "Tag Translation",
  "app.action.tags": "Tags",
  "app.action.viewDatabase": "View Database",

  "settings.category.appearance": "Appearance",
  "settings.category.file": "Files",
  "settings.category.interface": "Interface",
  "settings.category.language": "Language",
  "settings.category.network": "Network",
  "settings.category.shortcut": "Shortcuts",
  "settings.file.convertImportedImagesToPng": "Convert imported images to PNG",
  "settings.file.fileStoragePath": "File storage path",
  "settings.file.fileStoragePlaceholder": "Enter file storage path",
  "settings.file.thumbnailStoragePath": "Thumbnail cache path",
  "settings.file.thumbnailStoragePlaceholder": "Enter thumbnail cache path",
  "settings.interface.browser": "Browser",
  "settings.interface.browserPageSize": "Files per page",
  "settings.interface.browserPageSizePlaceholder": "Enter files per page",
  "settings.interface.configName": "Config name",
  "settings.interface.configNamePlaceholder": "Enter config name",
  "settings.interface.defaultImportPage": "Default import page",
  "settings.interface.defaultNewPage": "Default new page",
  "settings.interface.deleteConfig": "Delete config",
  "settings.interface.layoutConfigCount": "{count} configs",
  "settings.interface.layoutConfigNotLoaded": "Not loaded",
  "settings.interface.newConfig": "New config",
  "settings.interface.pageLayout": "Page layouts",
  "settings.language.interfaceLanguage": "Interface language",
  "settings.language.languageSettings": "Language settings",
  "settings.network.enableProxy": "Enable proxy",
  "settings.network.proxyAddress": "Proxy address",
  "settings.network.proxyAddressPlaceholder":
    "Enter proxy address, e.g. 127.0.0.1",
  "settings.network.proxyPort": "Proxy port",
  "settings.network.proxyPortPlaceholder": "Enter proxy port",
  "settings.shortcut.deleteShortcut": "Delete shortcut",
  "settings.shortcut.recording": "Press keys...",
  "settings.shortcut.resetDefaults": "Reset defaults",
  "settings.shortcut.closeWindow": "Close current window",
  "settings.shortcut.closeWindowDesc": "Except the main window",
  "settings.shortcut.selectAll": "Select all current items",
  "settings.shortcut.selectAllDesc":
    "Only applies to the current multi-select area",
  "settings.shortcut.detailPreviousFile": "Previous file in detail",
  "settings.shortcut.detailPreviousFileDesc": "File detail window",
  "settings.shortcut.detailNextFile": "Next file in detail",
  "settings.shortcut.detailNextFileDesc": "File detail window",
  "settings.shortcut.browserPreviousPage": "Previous browser page",
  "settings.shortcut.browserPreviousPageDesc": "Browser view",
  "settings.shortcut.browserNextPage": "Next browser page",
  "settings.shortcut.browserNextPageDesc": "Browser view",
  "settings.theme.theme": "Theme",
  "settings.theme.themeSettings": "Theme settings",
  "settings.theme.default": "Default theme",
  "settings.theme.light": "Light theme",
  "window.dialog.loading": "Loading",
  "window.export.failed": "Export failed",
  "window.export.file": "Files",
  "window.export.filename": "Filename",
  "window.export.inputFormat": "Enter export filename format",
  "window.export.inputPath": "Enter export path",
  "window.export.noFormat": "No format",
  "window.export.path": "Path",
  "window.export.waiting": "Waiting for export",
  "window.batchOperation.title": "Batch Operation",
  "window.batchOperation.loading": "Loading",
  "window.batchOperation.invalid": "Invalid file selection",
  "window.batchOperation.count": "{count} files, {imageCount} images",
  "window.batchOperation.processing": "Processing {current} / {total}: {name}",
  "window.batchOperation.complete": "Done: {count} images",
  "window.batchOperation.logs": "Process log",
  "window.batchOperation.noLogs": "No logs",
  "window.batchOperation.description":
    "The process function receives a context object that can read file metadata, tags, and URLs, and can edit tags and URLs in bulk.",
  "window.batchOperation.resetExample": "Reset example",
  "window.batchOperation.run": "Run",
  "window.batchOperation.running": "Processing",
  "window.batchOperation.compileFailed": "Script cannot run",
  "window.batchOperation.notFunction": "Script must return a function",
  "window.batchOperation.processFailed": "Processing failed",
  "window.batchOperation.metadataProcessed": "Metadata updated",
  "window.batchOperation.urlMissing": "URL does not exist",
  "window.batchTagManager.title": "Batch Tag Manager",
  "window.fileRatingEditor.title": "Set Rating",
  "window.favorite.fileCount": "{count} files",
  "window.favorite.updateFailed": "Failed to update favorite",
  "window.favorite.noFiles": "No favorite files",
  "window.translation.csvHint": "CSV format: 1girl,0,1个女孩",
  "window.translation.csvPlaceholder": "Enter tag translation CSV path",
  "window.translation.csvPath": "Tag translation CSV path",
  "window.translation.enableMenu": "Enable context menu tag translation",
  "window.translation.file": "Translation file",
  "window.translation.notLoaded": "Not loaded",
  "window.translation.keepOriginal": "Keep original tags in database",
  "window.translation.loaded": "Settings loaded",
  "window.translation.saved": "Settings saved",
  "window.translation.translateOnCreate": "Try translate when creating tags",
  "window.url.add": "Add",
  "window.url.addInput": "Add URL",
  "window.url.addPlaceholder": "Enter URL to add",
  "window.url.edit": "Edit",
  "window.url.invalidFile": "Invalid file",
  "window.url.list": "URL list",
  "window.url.loadFailed": "Load failed",
  "window.url.noUrl": "No URL",
  "window.url.sharedList": "{count} files shared URLs",
  "window.url.title": "URL Manager",
  "window.database.loading": "Loading",
  "window.database.readonly": "Read only",
  "window.database.loadFailed": "Load failed",
  "window.database.noRecords": "No file records",
  "window.database.id": "ID",
  "window.database.extension": "Extension",
  "window.database.size": "Size",
  "window.database.importedAt": "Imported at",
  "window.database.pageSummary":
    "Page {page} / {totalPages}, {total} files, {message}",
  "window.database.previous": "Previous",
  "window.database.next": "Next",
  "window.api.loading": "Loading",
  "window.api.preloadUnavailable": "preload unavailable",
  "window.api.serviceList": "Service list",
  "window.api.noServices": "No API services",
  "window.api.createInput": "New API",
  "window.api.createPlaceholder": "Enter API name",
  "window.api.create": "Create",
  "window.api.defaultServiceName": "API Service",
  "window.api.enable": "Enable",
  "window.api.delete": "Delete",
  "window.api.check": "Check",
  "window.api.name": "Name",
  "window.api.address": "Address",
  "window.api.port": "Port",
  "window.api.token": "Token",
  "window.api.permissions": "Permissions",
  "window.api.noServiceSelected": "Please create an API service",
  "window.api.success": "{count} API services",
  "window.api.deleted": "Deleted",
  "window.api.namePlaceholder": "Enter API name",
  "window.api.addressPlaceholder": "Enter API address",
  "window.api.portPlaceholder": "Enter API port",
  "window.api.tokenPlaceholder": "Enter token",
  "window.rating.loading": "Loading",
  "window.rating.preloadUnavailable": "preload unavailable",
  "window.rating.group": "Rating",
  "window.rating.noGroups": "No ratings",
  "window.rating.createInput": "New rating",
  "window.rating.createPlaceholder": "Enter rating to create",
  "window.rating.create": "Create",
  "window.rating.name": "Rating name",
  "window.rating.namePlaceholder": "Enter rating name",
  "window.rating.rename": "Rename",
  "window.rating.activate": "Activate",
  "window.rating.deactivate": "Disable",
  "window.rating.delete": "Delete",
  "window.rating.entryInput": "New entry",
  "window.rating.entryPlaceholder": "Enter rating entry",
  "window.rating.entryCreate": "New entry",
  "window.rating.entryColor": "Entry color",
  "window.rating.entryCount": "{count} entries",
  "window.rating.noEntries": "No entries",
  "window.rating.dragHint": "Drag to reorder",
  "window.recycle.loading": "Loading",
  "window.recycle.preloadUnavailable": "preload unavailable",
  "window.recycle.confirmDeleteTitle": "Confirm permanent deletion",
  "window.recycle.confirmDeleteMessage": "Delete {count} files permanently?",
  "window.recycle.confirmClearTitle": "Confirm empty recycle bin",
  "window.recycle.confirmClearMessage":
    "Delete all {count} files in the recycle bin permanently?",
  "window.recycle.noRecords": "No file records",
  "window.recycle.restore": "Restore",
  "window.recycle.delete": "Delete permanently",
  "window.recycle.restoreAll": "Restore all",
  "window.recycle.deleteAll": "Delete all permanently",
  "window.recycle.previous": "Previous",
  "window.recycle.next": "Next",
  "window.batch.loading": "Loading",
  "window.batch.invalid": "Invalid file",
  "window.batch.count": "{count} files",
  "window.batch.noTags": "No tags",
  "window.batch.input": "Enter tags",
  "window.batch.placeholder": "Enter tags to add",
  "window.fileRating.loading": "Loading",
  "window.fileRating.invalid": "Invalid parameters",
  "window.fileRating.missing": "Rating does not exist",
  "window.fileRating.loadFailed": "Load failed",
  "window.fileRating.group": "Rating",
  "window.fileRating.files": "{count} files",
  "window.fileRating.noEntries": "No entries",
  "window.fileRating.cancel": "Cancel",
  "window.fileRating.save": "Save",
  "window.tagManager.loading": "Loading",
  "window.tagManager.loadedStyle": "{count} styles",
  "window.tagManager.createdStyle": "Style created",
  "window.tagManager.createFailed": "Creation failed",
  "window.tagManager.createdTags": "Created {count} tags",
  "window.tagManager.activatedStyle": "Style enabled",
  "window.tagManager.activateFailed": "Enable failed",
  "window.tagManager.renamedStyle": "Style renamed",
  "window.tagManager.renameFailed": "Rename failed",
  "window.tagManager.confirmDeleteStyleTitle": "Confirm delete tag style",
  "window.tagManager.confirmDeleteStyleMessage":
    "This will delete {count} tags under style “{name}” and remove related file tag links. Continue?",
  "window.tagManager.deletedStyle": "Deleted style, removed {count} tags",
  "window.tagManager.deleteStyleFailed": "Failed to delete style",
  "window.tagManager.confirmDeleteTagsTitle": "Confirm delete tags",
  "window.tagManager.deletedTags":
    "Deleted {tagCount} tags, affected {fileCount} files",
  "window.tagManager.deleteFailed": "Delete failed",
  "window.tagManager.styleList": "Tag styles",
  "window.tagManager.currentStyleTags": "Current style tags",
  "window.tagManager.searchTags": "Search tags",
  "window.tagManager.searchTagsPlaceholder": "Search current style tags",
  "window.tagManager.newStyle": "New style",
  "window.tagManager.newStylePlaceholder": "Enter style to create",
  "window.tagManager.create": "Create",
  "window.tagManager.renameStyle": "Rename style",
  "window.tagManager.renameStylePlaceholder": "Enter style to rename",
  "window.tagManager.rename": "Rename",
  "window.tagManager.deleteStyle": "Delete",
  "window.tagManager.sortField": "Sort field",
  "window.tagManager.sortName": "Name",
  "window.tagManager.sortCreatedAt": "Created at",
  "window.tagManager.sortFileCount": "File count",
  "window.tagManager.sortDirection": "Sort direction",
  "window.tagManager.sortAsc": "Ascending",
  "window.tagManager.sortDesc": "Descending",
  "window.tagManager.enableStyle": "Enable style",
  "window.tagManager.noTags": "No tags",
  "window.tagManager.selectedCount": "{count} selected tags",
  "window.tagManager.delete": "Delete",
  "window.tagManager.parents": "Parent semantics",
  "window.tagManager.parentAddFailed": "Failed to add parent relation",
  "window.tagManager.parentRemoveFailed": "Failed to remove parent relation",
  "window.tagManager.parentRelationsAdded": "Added {count} relations",
  "window.tagManager.parentRelationsRemoved": "Removed {count} relations",
  "window.tagManager.relationErrorTitle": "Tag relation error",
  "window.tagManager.parentSelfRelation": "A tag cannot be its own parent",
  "window.tagManager.siblingSelfRelation":
    "An alias tag cannot point to itself",
  "window.tagManager.noStyleSelected": "No tag style selected",
  "window.tagManager.styleSummary": "{count} tags",
  "window.tagManager.stagingArea": "Staging area",
  "window.tagManager.stagingCount": "{count} staged tags",
  "window.tagManager.noStagedTags": "No staged tags",
  "window.tagManager.basicInfo": "Basic info",
  "window.tagManager.tagRelations": "Tag relations",
  "window.tagManager.existingTags": "Existing tags",
  "window.tagManager.tagsToCreate": "Tags to create",
  "window.tagManager.createTagInput": "Create tag",
  "window.tagManager.createTagPlaceholder": "Type a new tag to create",
  "window.tagManager.tagAlreadyExists": "Tag already exists",
  "window.tagManager.tagAlreadyPendingCreate":
    "Tag is already in the create list",
  "window.tagManager.invalidTagInput": "Enter a valid tag",
  "window.tagManager.nameColumn": "Name",
  "window.tagManager.fileCountColumn": "File count",
  "window.tagManager.createdAtColumn": "Created at",
  "window.tagManager.operationColumn": "Actions",
  "window.tagManager.noExistingStagedTags": "No existing staged tags",
  "window.tagManager.noMissingStagedTags": "No tags to create",
  "window.tagManager.stagedTags": "Staged {count} tags",
  "window.tagManager.renameTag": "Rename tag",
  "window.tagManager.renamedTag": "Tag renamed",
  "window.tagManager.renamePreview": "Impact preview",
  "window.tagManager.renamePreviewLoading": "Calculating impact",
  "window.tagManager.renamePreviewFailed": "Failed to preview impact",
  "window.tagManager.renamePreviewFiles":
    "Directly affects {directCount} files; semantic search can match {effectiveCount} files, including {impliedCount} inferred files.",
  "window.tagManager.renamePreviewParents":
    "{parentCount} parent relations and {childCount} child relations.",
  "window.tagManager.renamePreviewSiblings":
    "As canonical: {aliasCount} aliases; as alias: {canonicalCount} canonical targets.",
  "window.tagManager.renamePreviewDuplicate":
    "The target tag already exists, so saving will fail.",
  "window.tagManager.invalidTag": "Invalid tag",
  "window.tagManager.confirmDeleteSingleTagMessage":
    "This will delete “{name}” and remove it from related files. Continue?",
  "window.tagManager.relationSourceTags": "Operation tags",
  "window.tagManager.addParentInput": "Add parent tag",
  "window.tagManager.addChildInput": "Add child tag",
  "window.tagManager.addParentPlaceholder": "Type to add parent",
  "window.tagManager.addChildPlaceholder": "Type to add child",
  "window.tagManager.addRelation": "Add",
  "window.tagManager.noRelationSourceSelected": "Select operation tags first",
  "window.tagManager.noCommonParents": "No common parent tags",
  "window.tagManager.noCommonChildren": "No common child tags",
  "window.tagManager.setSelectedChildren": "Set selected tags as children",
  "window.tagManager.commonParents": "Common parent tags",
  "window.tagManager.setSelectedParents": "Set selected tags as parents",
  "window.tagManager.commonChildren": "Common child tags",
  "window.tagManager.selectedRelationTags": "Selected tags",
  "window.tagManager.removeRelation": "Remove",
  "window.tagManager.openRelationTree": "Open relation tree",
  "window.tagManager.noRelationTreeTags": "No relation tree tags to open",
  "window.tagManager.aliasesAndCanonical": "Aliases and canonical",
  "window.tagManager.setSelectedAliases": "Set selected tags as aliases",
  "window.tagManager.setCanonicalInput": "Set canonical tag",
  "window.tagManager.setCanonicalPlaceholder": "Type to set canonical",
  "window.tagManager.setCanonical": "Set canonical",
  "window.tagManager.commonCanonical": "Common canonical tag",
  "window.tagManager.addAliasesToCanonical": "Add aliases to canonical",
  "window.tagManager.addAliasesInput": "Add alias tags",
  "window.tagManager.addAliasesPlaceholder": "Type to add aliases",
  "window.tagManager.selectSingleCanonicalTag": "Select one canonical tag",
  "window.tagManager.addAliases": "Add aliases",
  "window.tagManager.aliasesOfSelectedTags": "Aliases of selected tags",
  "window.tagManager.removeSibling": "Remove",
  "window.tagManager.noCommonCanonicalTags": "No common canonical tag",
  "window.tagManager.noAliasTags": "No alias tags",
  "window.tagManager.siblingsSet": "Set {count} canonical tags",
  "window.tagManager.siblingsRemoved": "Removed {count} alias relations",
  "window.tagManager.siblingSetFailed": "Failed to set canonical tag",
  "window.tagManager.siblingRemoveFailed": "Failed to remove alias relation",
  "window.tagRelationTree.title": "Tag Relation Tree",
  "window.tagRelationTree.siblingTitle": "Tag Alias Relation Tree",
  "window.tagRelationTree.loading": "Loading relation tree",
  "window.tagRelationTree.loadFailed": "Failed to load relation tree",
  "window.tagRelationTree.noSelection": "No tags selected",
  "window.tagRelationTree.loaded": "{nodeCount} tags, {edgeCount} relations",
  "window.tagRelationTree.summary":
    "Selected {selectedCount}, nodes {nodeCount}, relations {edgeCount}",
  "window.tagRelationTree.fit": "Fit",
  "window.tagRelationTree.readonly": "Read-only relation tree",
  "window.ai.loading": "Loading",
  "window.ai.loaded": "Settings loaded",
  "window.ai.saved": "Settings saved",
  "window.ai.detecting": "Detecting models",
  "window.ai.detected": "Detected {count} models",
  "window.ai.noModel": "No models detected",
  "window.ai.downloading": "Downloading default model",
  "window.ai.ready": "Default model is ready",
  "window.ai.noModelDetected": "No models detected",
  "window.ai.modelConfig": "Model Config",
  "window.ai.featureConfig": "Feature Config",
  "window.ai.path": "Path",
  "window.ai.pathPlaceholder": "Enter model folder path",
  "window.ai.detectModel": "Detect Model",
  "window.ai.downloadDefault": "Download Default",
  "window.ai.model": "Model",
  "window.ai.selectModel": "Select model",
  "window.ai.noneSelected": "Not selected",
  "window.ai.generalThreshold": "General threshold",
  "window.ai.characterThreshold": "Character threshold",
  "window.ai.thresholdPlaceholder": "Enter 0-1",
  "window.ai.info": "Model Info",
  "window.ai.modelName": "Model name",
  "window.ai.modelCount": "Model count",
  "window.ai.modelSize": "Model size",
  "window.ai.enableAutoTag":
    "Use model tagging when imported images have no tags",
  "window.ai.enableRetag":
    "Enable context menu retag selected images (overwrite)",
  "window.ai.enableAppend": "Enable context menu tag selected images (append)",
  "window.hydrus.loading": "Loading",
  "window.hydrus.waiting": "Waiting",
  "window.hydrus.preloadUnavailable":
    "preload unavailable, please restart the app",
  "window.hydrus.preloadAvailable": "preload available",
  "window.hydrus.loaded": "Settings loaded",
  "window.hydrus.saved": "Settings saved",
  "window.hydrus.testConnectionIgnored":
    "Test connection ignored: task running",
  "window.hydrus.apiUnavailable":
    "Hydrus import API unavailable, please restart the app",
  "window.hydrus.testingConnection": "Testing connection",
  "window.hydrus.testConnection": "Test connection",
  "window.hydrus.connectionSucceeded": "Connection succeeded: {message}",
  "window.hydrus.connectionFailed": "Connection failed: {message}",
  "window.hydrus.testConnectionFailed": "Test connection failed",
  "window.hydrus.startImportIgnored": "Import ignored: task running",
  "window.hydrus.importMissing": "importFromHydrus is unavailable",
  "window.hydrus.preparingImport": "Preparing Hydrus import",
  "window.hydrus.importSummary":
    "Import finished: added={imported} duplicates={duplicated} skipped={skipped} failed={failed}",
  "window.hydrus.importFailed": "Hydrus import failed",
  "window.hydrus.startImport": "Start import",
  "window.hydrus.cancelImport": "Cancel",
  "window.hydrus.address": "Address",
  "window.hydrus.addressPlaceholder": "Enter Hydrus API address",
  "window.hydrus.accessKey": "Access Key",
  "window.hydrus.accessKeyPlaceholder": "Enter Hydrus Access Key",
  "window.hydrus.tagStyle": "Tag style",
  "window.hydrus.tagStylePlaceholder": "Enter the migration tag style",
  "window.hydrus.limit": "Limit",
  "window.hydrus.limitPlaceholder": "0 means unlimited",
  "window.hydrus.metadataBatchSize": "Metadata batch",
  "window.hydrus.metadataBatchSizePlaceholder": "Enter metadata batch size",
  "window.hydrus.duplicateAsNewObject": "Create new object for duplicate files",
  "window.hydrus.searchTags": "Search tags",
  "window.hydrus.searchTagsPlaceholder":
    "Enter Hydrus search tags, separated by commas or new lines; blank means all",
  "window.hydrus.total": "Total",
  "window.hydrus.processed": "Processed",
  "window.hydrus.added": "Added",
  "window.hydrus.duplicated": "Duplicates",
  "window.hydrus.skipped": "Skipped",
  "window.hydrus.failed": "Failed",
  "window.hydrus.current": "Current",
  "window.hydrus.connectionStatus": "Connection status",
  "window.hydrus.permissions": "Permissions",
  "window.hydrus.notTested": "Not tested",
  "window.hydrus.debug": "Debug",
  "window.hydrus.clear": "Clear",
  "window.hydrus.noDebugInfo": "No debug information",
  "window.ehentai.loading": "Loading",
  "window.ehentai.waiting": "Waiting",
  "window.ehentai.preloadUnavailable":
    "preload unavailable, please restart the app",
  "window.ehentai.loaded": "Settings loaded",
  "window.ehentai.saved": "Settings saved",
  "window.ehentai.apiUnavailable":
    "E-Hentai API unavailable, please restart the app",
  "window.ehentai.detectingGalleryLink": "Detecting gallery link",
  "window.ehentai.testingGallery": "Testing link",
  "window.ehentai.detectSuccess": "Detection succeeded: {message}",
  "window.ehentai.detectFailed": "Detection failed: {message}",
  "window.ehentai.detectException": "Detection exception: {message}",
  "window.ehentai.preparingImport": "Preparing E-Hentai import",
  "window.ehentai.importSummary":
    "Import finished: added={imported} duplicates={duplicated} failed={failed}",
  "window.ehentai.importFailed": "E-Hentai import failed",
  "window.ehentai.importException": "Import exception: {message}",
  "window.ehentai.startImport": "Start import",
  "window.ehentai.cancelImport": "Cancel",
  "window.ehentai.testGallery": "Test link",
  "window.ehentai.galleryUrl": "Gallery URL",
  "window.ehentai.galleryUrlPlaceholder": "Enter https://e-hentai.org/g/...",
  "window.ehentai.cookie": "Cookie",
  "window.ehentai.cookiePlaceholder":
    "Paste the cookie copied from the browser",
  "window.ehentai.importGalleryTags": "Import gallery tags",
  "window.ehentai.duplicateAsNewObject":
    "Create new object for duplicate files",
  "window.ehentai.startIndex": "Start index",
  "window.ehentai.startIndexHint":
    "Start from which image in the gallery. Minimum is 1. After interruption, continue with the next image index.",
  "window.ehentai.limit": "Limit",
  "window.ehentai.limitPlaceholder": "0 means unlimited",
  "window.ehentai.limitHint":
    "Maximum images to import this time. 0 means import from the start index to the end.",
  "window.ehentai.requestTimeout": "Request timeout ms",
  "window.ehentai.total": "Total",
  "window.ehentai.processed": "Processed",
  "window.ehentai.added": "Added",
  "window.ehentai.duplicated": "Duplicates",
  "window.ehentai.skipped": "Skipped",
  "window.ehentai.failed": "Failed",
  "window.ehentai.current": "Current",
  "window.ehentai.galleryStatus": "Gallery status",
  "window.ehentai.imageCount": "First page: {count}",
  "window.ehentai.style": "Style: e-hentai",
  "window.ehentai.notDetected": "Not detected",
  "window.ehentai.importRules": "Import rules",
  "window.ehentai.ruleDescription":
    "By default, the e-hentai style tag gallery:gallery name is written. If import gallery tags is enabled, page tags are also written. Duplicate files are skipped by default; enabling duplicate files to create a new object reuses the physical file. The request cooldown is fixed at 10000ms.",
  "window.ehentai.logs": "Logs",
  "window.ehentai.clear": "Clear",
  "window.ehentai.noLogs": "No logs",
  "window.fileDetail.invalid": "Invalid file",
  "window.fileDetail.notFound": "File not found",
  "window.fileDetail.loadFailed": "Load failed",
  "window.fileDetail.favoriteUpdateFailed": "Failed to update favorite",
  "window.fileDetail.movedToRecycleBin": "File moved to recycle bin",
  "window.fileDetail.filterComplete": "Filtering complete",
  "window.fileDetail.cannotPreview": "Cannot preview",
  "window.fileDetail.tags": "File tags",
  "window.fileDetail.inferredTags": "Inferred tags",
  "window.fileDetail.inferredTagTitle": "{tag}, inferred from parent relations",
  "window.fileDetail.canonicalTagTitle":
    "{tag}, mapped to canonical tag by alias relation",
  "window.fileDetail.addTags": "Enter tags to add",
  "window.fileDetail.title": "File Detail",

  "window.import.now": "Import now",
  "window.import.cancel": "Cancel",
  "window.import.dropHint": "Release to import media files or folders",
  "window.import.batch": "Batch",
  "window.import.total": "Total",
  "window.import.ready": "Ready",
  "window.import.added": "Added",
  "window.import.duplicate": "Duplicate",
  "window.import.failed": "Failed",
  "window.import.chunk": "Chunk",
  "window.import.currentFile": "Current file",
  "window.import.status": "Status",
  "window.import.size": "Size",
  "window.import.extension": "Extension",
  "window.import.path": "Path",
  "window.import.noFiles": "No files to import",
  "window.search.locked": "Unavailable while files are being imported",
  "window.search.input": "Search",
  "window.search.placeholder": "Enter tags to search",
  "window.search.noFilters": "No filters",
  "window.screening.title": "Screening Import",
  "window.browser.loading": "Loading",
  "window.browser.loadFailed": "Load failed",
  "window.browser.favoriteFailed": "Failed to update favorite",
  "window.browser.pendingCount": "{count} pending import files",
  "window.browser.resultCount": "{count} results",
  "window.browser.fileCount": "{count} files",
  "window.browser.noRecords": "No file records",
  "window.browser.pending": "Pending",
  "window.browser.sort": "Sort",
  "window.browser.sortField": "Browser sort field",
  "window.browser.sortDirection": "Browser sort direction",
  "window.browser.importedAt": "Imported date",
  "window.browser.updatedAt": "Updated date",
  "window.browser.desc": "Descending",
  "window.browser.asc": "Ascending",
  "window.browser.firstPage": "First",
  "window.browser.previousPage": "Prev",
  "window.browser.pageInput": "Browser page",
  "window.browser.nextPage": "Next",
  "window.browser.lastPage": "Last",
  "window.contextMenu.manageUrl": "Manage URL",
  "window.contextMenu.manageTags": "Manage tags",
  "window.contextMenu.batchOperate": "Batch operation",
  "window.contextMenu.openDefault": "Open with default app",
  "window.contextMenu.aiRetagOverwrite": "Use AI tagging (overwrite)",
  "window.contextMenu.aiRetagAppend": "Use AI tagging (append)",
  "window.contextMenu.translateTags": "Translate tags",
  "window.contextMenu.export": "Export",
  "window.contextMenu.screening": "Screening import",
  "window.contextMenu.ratingSet": "Set:{name}",
  "window.contextMenu.trash": "Move to recycle bin",
  "window.tagList.loading": "Loading",
  "window.tagList.preloadUnavailable": "preload unavailable",
  "window.tagList.loadedTags": "{count} tags",
  "window.tagList.loadFailed": "Load failed",
  "window.tagList.displayRange": "Tag display scope",
  "window.tagList.all": "All",
  "window.tagList.namespace": "Namespace",
  "window.tagList.plain": "Plain tags",
  "window.tagList.selection": "Selection",
  "window.tagList.sortAlphabetical": "Alphabetical sort",
  "window.tagList.ascending": "Ascending",
  "window.tagList.descending": "Descending",
  "window.tagList.namespaceFirst": "Namespace first",
  "window.tagList.locked": "Unavailable while files are being imported",
  "window.tagList.domains": "Domains",
  "window.tagList.noDomains": "No domains",
  "window.tagList.noTags": "No tags",
};

const translationTables: Record<LanguageId, Record<TranslationKey, string>> = {
  "zh-CN": zhCNTranslations,
  "en-US": enUSTranslations,
};

let currentLanguageId: LanguageId = "zh-CN";

export const languageDefinitions: LanguageDefinition[] = [
  {
    id: "zh-CN",
    name: "简体中文",
    htmlLang: "zh-CN",
    direction: "ltr",
  },
  {
    id: "en-US",
    name: "English",
    htmlLang: "en-US",
    direction: "ltr",
  },
];

export const languageOptions = languageDefinitions.map((language) => ({
  id: language.id,
  name: language.name,
}));

export function loadLanguageSettings(): LanguageSettings {
  const rawSettings = window.localStorage.getItem(LANGUAGE_SETTINGS_KEY);

  if (!rawSettings) {
    const settings = createDefaultLanguageSettings();
    currentLanguageId = settings.languageId;
    return settings;
  }

  try {
    const settings = normalizeLanguageSettings(JSON.parse(rawSettings));
    currentLanguageId = settings.languageId;
    return settings;
  } catch {
    const settings = createDefaultLanguageSettings();
    currentLanguageId = settings.languageId;
    return settings;
  }
}

export function saveLanguageSettings(
  settings: LanguageSettings,
): LanguageSettings {
  const normalizedSettings = normalizeLanguageSettings(settings);
  window.localStorage.setItem(
    LANGUAGE_SETTINGS_KEY,
    JSON.stringify(normalizedSettings),
  );
  applyLanguage(normalizedSettings.languageId);
  window.dispatchEvent(new CustomEvent(LANGUAGE_SETTINGS_EVENT));

  try {
    const channel = new BroadcastChannel(LANGUAGE_SETTINGS_CHANNEL);
    channel.postMessage(normalizedSettings);
    channel.close();
  } catch {
    // BroadcastChannel is best-effort; storage still persists the setting.
  }

  return normalizedSettings;
}

export function listenLanguageSettingsChanged(
  listener: (settings: LanguageSettings) => void,
): () => void {
  const handleChange = (): void => {
    listener(loadLanguageSettings());
  };

  const handleStorage = (event: StorageEvent): void => {
    if (event.key === LANGUAGE_SETTINGS_KEY) {
      handleChange();
    }
  };

  window.addEventListener(LANGUAGE_SETTINGS_EVENT, handleChange);
  window.addEventListener("storage", handleStorage);

  let channel: BroadcastChannel | null = null;

  try {
    channel = new BroadcastChannel(LANGUAGE_SETTINGS_CHANNEL);
    channel.addEventListener("message", handleChange);
  } catch {
    channel = null;
  }

  return () => {
    window.removeEventListener(LANGUAGE_SETTINGS_EVENT, handleChange);
    window.removeEventListener("storage", handleStorage);
    channel?.removeEventListener("message", handleChange);
    channel?.close();
  };
}

export function applySavedLanguage(): void {
  applyLanguage(loadLanguageSettings().languageId);
}

export function applyLanguage(languageId: LanguageId): void {
  const language = getLanguageDefinition(languageId);
  const root = document.documentElement;

  currentLanguageId = language.id;
  root.lang = language.htmlLang;
  root.dir = language.direction;
  root.dataset.language = language.id;
}

export function translate(
  key: TranslationKey,
  values?: TranslationValues,
): string {
  return translateWithLanguage(currentLanguageId, key, values);
}

export function createTranslator(languageId: LanguageId): TranslationFunction {
  return (key, values) => translateWithLanguage(languageId, key, values);
}

export function getFileDomainDisplayName(
  domain: FileDomain,
  t: TranslationFunction,
): string {
  if (domain === "library") {
    return t("app.domain.library");
  }

  if (domain === "trash") {
    return t("app.domain.trash");
  }

  return t("app.domain.pending");
}

export function useLanguage(): {
  languageId: LanguageId;
  t: TranslationFunction;
} {
  const languageId = useSyncExternalStore(
    subscribeLanguageSettings,
    getLanguageSnapshot,
    getLanguageSnapshot,
  );
  const t = useMemo(() => createTranslator(languageId), [languageId]);

  return { languageId, t };
}

function createDefaultLanguageSettings(): LanguageSettings {
  return {
    languageId: "zh-CN",
  };
}

function normalizeLanguageSettings(value: unknown): LanguageSettings {
  const settings = value as Partial<LanguageSettings> | null;
  const languageId = isLanguageId(settings?.languageId)
    ? settings.languageId
    : "zh-CN";

  return { languageId };
}

function isLanguageId(value: unknown): value is LanguageId {
  return languageDefinitions.some((language) => language.id === value);
}

function getLanguageDefinition(languageId: LanguageId): LanguageDefinition {
  return (
    languageDefinitions.find((language) => language.id === languageId) ??
    languageDefinitions[0]!
  );
}

function subscribeLanguageSettings(onStoreChange: () => void): () => void {
  return listenLanguageSettingsChanged(() => onStoreChange());
}

function getLanguageSnapshot(): LanguageId {
  return loadLanguageSettings().languageId;
}

function translateWithLanguage(
  languageId: LanguageId,
  key: TranslationKey,
  values?: TranslationValues,
): string {
  const template =
    translationTables[languageId]?.[key] ?? translationTables["zh-CN"][key];

  return formatTranslation(template, values);
}

function formatTranslation(
  template: string,
  values?: TranslationValues,
): string {
  if (!values) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    values[name] === undefined ? match : String(values[name]),
  );
}
